//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ons {

public class MessageQueueONS : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MessageQueueONS(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MessageQueueONS obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MessageQueueONS() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ONSClient4CPPPINVOKE.delete_MessageQueueONS(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MessageQueueONS() : this(ONSClient4CPPPINVOKE.new_MessageQueueONS__SWIG_0(), true) {
  }

  public MessageQueueONS(string topic, string brokerName, int queueId) : this(ONSClient4CPPPINVOKE.new_MessageQueueONS__SWIG_1(topic, brokerName, queueId), true) {
    if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending) throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
  }

  public MessageQueueONS(MessageQueueONS other) : this(ONSClient4CPPPINVOKE.new_MessageQueueONS__SWIG_2(MessageQueueONS.getCPtr(other)), true) {
    if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending) throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getTopic() {
    string ret = ONSClient4CPPPINVOKE.MessageQueueONS_getTopic(swigCPtr);
    return ret;
  }

  public void setTopic(string topic) {
    ONSClient4CPPPINVOKE.MessageQueueONS_setTopic(swigCPtr, topic);
    if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending) throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getBrokerName() {
    string ret = ONSClient4CPPPINVOKE.MessageQueueONS_getBrokerName(swigCPtr);
    return ret;
  }

  public void setBrokerName(string brokerName) {
    ONSClient4CPPPINVOKE.MessageQueueONS_setBrokerName(swigCPtr, brokerName);
    if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending) throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getQueueId() {
    int ret = ONSClient4CPPPINVOKE.MessageQueueONS_getQueueId(swigCPtr);
    return ret;
  }

  public void setQueueId(int queueId) {
    ONSClient4CPPPINVOKE.MessageQueueONS_setQueueId(swigCPtr, queueId);
  }

  public int compareTo(MessageQueueONS mq) {
    int ret = ONSClient4CPPPINVOKE.MessageQueueONS_compareTo(swigCPtr, MessageQueueONS.getCPtr(mq));
    if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending) throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
