//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ons {

public class MessageOrderListener : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MessageOrderListener(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MessageOrderListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MessageOrderListener() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ONSClient4CPPPINVOKE.delete_MessageOrderListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MessageOrderListener() : this(ONSClient4CPPPINVOKE.new_MessageOrderListener(), true) {
    SwigDirectorConnect();
  }

  public virtual OrderAction consume(Message message, ConsumeOrderContext context) {
    OrderAction ret = (OrderAction)ONSClient4CPPPINVOKE.MessageOrderListener_consume(swigCPtr, Message.getCPtr(message), ConsumeOrderContext.getCPtr(context));
    if (ONSClient4CPPPINVOKE.SWIGPendingException.Pending) throw ONSClient4CPPPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("consume", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateMessageOrderListener_0(SwigDirectorconsume);
    ONSClient4CPPPINVOKE.MessageOrderListener_director_connect(swigCPtr, swigDelegate0);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(MessageOrderListener));
    return hasDerivedMethod;
  }

  private int SwigDirectorconsume(global::System.IntPtr message, global::System.IntPtr context) {
    return (int)consume(new Message(message, false), new ConsumeOrderContext(context, false));
  }

  public delegate int SwigDelegateMessageOrderListener_0(global::System.IntPtr message, global::System.IntPtr context);

  private SwigDelegateMessageOrderListener_0 swigDelegate0;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(Message), typeof(ConsumeOrderContext) };
}

}
