//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ons {

class ONSClient4CPPPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="SWIGRegisterExceptionCallbacks_ONSClient4CPP")]
    public static extern void SWIGRegisterExceptionCallbacks_ONSClient4CPP(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_ONSClient4CPP")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_ONSClient4CPP(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_ONSClient4CPP(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_ONSClient4CPP(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(ONSClient4CPPPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(ONSClient4CPPPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="SWIGRegisterStringCallback_ONSClient4CPP")]
    public static extern void SWIGRegisterStringCallback_ONSClient4CPP(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_ONSClient4CPP(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static ONSClient4CPPPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_SystemPropKey")]
  public static extern global::System.IntPtr new_SystemPropKey();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_SystemPropKey")]
  public static extern void delete_SystemPropKey(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_TAG_set")]
  public static extern void SystemPropKey_TAG_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_TAG_get")]
  public static extern string SystemPropKey_TAG_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_KEY_set")]
  public static extern void SystemPropKey_KEY_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_KEY_get")]
  public static extern string SystemPropKey_KEY_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_MSGID_set")]
  public static extern void SystemPropKey_MSGID_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_MSGID_get")]
  public static extern string SystemPropKey_MSGID_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_RECONSUMETIMES_set")]
  public static extern void SystemPropKey_RECONSUMETIMES_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_RECONSUMETIMES_get")]
  public static extern string SystemPropKey_RECONSUMETIMES_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_STARTDELIVERTIME_set")]
  public static extern void SystemPropKey_STARTDELIVERTIME_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SystemPropKey_STARTDELIVERTIME_get")]
  public static extern string SystemPropKey_STARTDELIVERTIME_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_Message__SWIG_0")]
  public static extern global::System.IntPtr new_Message__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_Message__SWIG_1")]
  public static extern global::System.IntPtr new_Message__SWIG_1(string jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_Message__SWIG_3")]
  public static extern global::System.IntPtr new_Message__SWIG_3(string jarg1, uint jarg2, string jarg3, uint jarg4, string jarg5, uint jarg6);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_Message__SWIG_4")]
  public static extern global::System.IntPtr new_Message__SWIG_4(string jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_Message")]
  public static extern void delete_Message(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_Message__SWIG_5")]
  public static extern global::System.IntPtr new_Message__SWIG_5(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_putUserProperties")]
  public static extern void Message_putUserProperties(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getUserProperties__SWIG_0")]
  public static extern string Message_getUserProperties__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setUserProperties")]
  public static extern void Message_setUserProperties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getUserProperties__SWIG_1")]
  public static extern global::System.IntPtr Message_getUserProperties__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_putSystemProperties")]
  public static extern void Message_putSystemProperties(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getSystemProperties__SWIG_0")]
  public static extern string Message_getSystemProperties__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setSystemProperties")]
  public static extern void Message_setSystemProperties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getSystemProperties__SWIG_1")]
  public static extern global::System.IntPtr Message_getSystemProperties__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getTopic")]
  public static extern string Message_getTopic(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setTopic")]
  public static extern void Message_setTopic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getTag")]
  public static extern string Message_getTag(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setTag")]
  public static extern void Message_setTag(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getKey")]
  public static extern string Message_getKey(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setKey")]
  public static extern void Message_setKey(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getMsgID")]
  public static extern string Message_getMsgID(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setMsgID")]
  public static extern void Message_setMsgID(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getStartDeliverTime")]
  public static extern long Message_getStartDeliverTime(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setStartDeliverTime")]
  public static extern void Message_setStartDeliverTime(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getBody")]
  public static extern string Message_getBody(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getMsgBody")]
  public static extern string Message_getMsgBody(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setMsgBody")]
  public static extern void Message_setMsgBody(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setBody")]
  public static extern void Message_setBody(global::System.Runtime.InteropServices.HandleRef jarg1, [global::System.Runtime.InteropServices.In, global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPArray)]byte[] jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getReconsumeTimes")]
  public static extern int Message_getReconsumeTimes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setReconsumeTimes")]
  public static extern void Message_setReconsumeTimes(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getStoreTimestamp")]
  public static extern long Message_getStoreTimestamp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setStoreTimestamp")]
  public static extern void Message_setStoreTimestamp(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_toString")]
  public static extern string Message_toString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_toSystemString")]
  public static extern string Message_toSystemString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_toUserString")]
  public static extern string Message_toUserString(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_getQueueOffset")]
  public static extern long Message_getQueueOffset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Message_setQueueOffset")]
  public static extern void Message_setQueueOffset(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_MessageQueueONS__SWIG_0")]
  public static extern global::System.IntPtr new_MessageQueueONS__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_MessageQueueONS__SWIG_1")]
  public static extern global::System.IntPtr new_MessageQueueONS__SWIG_1(string jarg1, string jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_MessageQueueONS__SWIG_2")]
  public static extern global::System.IntPtr new_MessageQueueONS__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_getTopic")]
  public static extern string MessageQueueONS_getTopic(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_setTopic")]
  public static extern void MessageQueueONS_setTopic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_getBrokerName")]
  public static extern string MessageQueueONS_getBrokerName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_setBrokerName")]
  public static extern void MessageQueueONS_setBrokerName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_getQueueId")]
  public static extern int MessageQueueONS_getQueueId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_setQueueId")]
  public static extern void MessageQueueONS_setQueueId(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageQueueONS_compareTo")]
  public static extern int MessageQueueONS_compareTo(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_MessageQueueONS")]
  public static extern void delete_MessageQueueONS(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_ONSClientException__SWIG_0")]
  public static extern global::System.IntPtr new_ONSClientException__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_ONSClientException")]
  public static extern void delete_ONSClientException(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_ONSClientException__SWIG_1")]
  public static extern global::System.IntPtr new_ONSClientException__SWIG_1(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSClientException_GetMsg")]
  public static extern string ONSClientException_GetMsg(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSClientException_what")]
  public static extern string ONSClientException_what(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSClientException_GetError")]
  public static extern int ONSClientException_GetError(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_SendResultONS")]
  public static extern global::System.IntPtr new_SendResultONS();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_SendResultONS")]
  public static extern void delete_SendResultONS(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SendResultONS_setMessageId")]
  public static extern void SendResultONS_setMessageId(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_SendResultONS_getMessageId")]
  public static extern string SendResultONS_getMessageId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_PullResultONS__SWIG_0")]
  public static extern global::System.IntPtr new_PullResultONS__SWIG_0(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_PullResultONS__SWIG_1")]
  public static extern global::System.IntPtr new_PullResultONS__SWIG_1(int jarg1, long jarg2, long jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_PullResultONS")]
  public static extern void delete_PullResultONS(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_pullStatus_set")]
  public static extern void PullResultONS_pullStatus_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_pullStatus_get")]
  public static extern int PullResultONS_pullStatus_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_nextBeginOffset_set")]
  public static extern void PullResultONS_nextBeginOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_nextBeginOffset_get")]
  public static extern long PullResultONS_nextBeginOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_minOffset_set")]
  public static extern void PullResultONS_minOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_minOffset_get")]
  public static extern long PullResultONS_minOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_maxOffset_set")]
  public static extern void PullResultONS_maxOffset_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_maxOffset_get")]
  public static extern long PullResultONS_maxOffset_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_msgFoundList_set")]
  public static extern void PullResultONS_msgFoundList_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullResultONS_msgFoundList_get")]
  public static extern global::System.IntPtr PullResultONS_msgFoundList_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_ConsumeContext")]
  public static extern global::System.IntPtr new_ConsumeContext();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_ConsumeContext")]
  public static extern void delete_ConsumeContext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_ConsumeOrderContext")]
  public static extern global::System.IntPtr new_ConsumeOrderContext();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_ConsumeOrderContext")]
  public static extern void delete_ConsumeOrderContext(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_MessageOrderListener")]
  public static extern global::System.IntPtr new_MessageOrderListener();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_MessageOrderListener")]
  public static extern void delete_MessageOrderListener(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageOrderListener_consume")]
  public static extern int MessageOrderListener_consume(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageOrderListener_director_connect")]
  public static extern void MessageOrderListener_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, MessageOrderListener.SwigDelegateMessageOrderListener_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_MessageListener")]
  public static extern global::System.IntPtr new_MessageListener();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_MessageListener")]
  public static extern void delete_MessageListener(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageListener_consume")]
  public static extern int MessageListener_consume(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_MessageListener_director_connect")]
  public static extern void MessageListener_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, MessageListener.SwigDelegateMessageListener_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_LocalTransactionChecker")]
  public static extern global::System.IntPtr new_LocalTransactionChecker();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_LocalTransactionChecker_check")]
  public static extern int LocalTransactionChecker_check(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_LocalTransactionChecker")]
  public static extern void delete_LocalTransactionChecker(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_LocalTransactionChecker_director_connect")]
  public static extern void LocalTransactionChecker_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, LocalTransactionChecker.SwigDelegateLocalTransactionChecker_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_LocalTransactionExecuter")]
  public static extern global::System.IntPtr new_LocalTransactionExecuter();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_LocalTransactionExecuter_execute")]
  public static extern int LocalTransactionExecuter_execute(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_LocalTransactionExecuter")]
  public static extern void delete_LocalTransactionExecuter(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_LocalTransactionExecuter_director_connect")]
  public static extern void LocalTransactionExecuter_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, LocalTransactionExecuter.SwigDelegateLocalTransactionExecuter_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_Producer")]
  public static extern global::System.IntPtr new_Producer();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_Producer")]
  public static extern void delete_Producer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Producer_start")]
  public static extern void Producer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Producer_shutdown")]
  public static extern void Producer_shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Producer_send__SWIG_0")]
  public static extern global::System.IntPtr Producer_send__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Producer_send__SWIG_1")]
  public static extern global::System.IntPtr Producer_send__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Producer_sendOneway")]
  public static extern void Producer_sendOneway(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_Producer_director_connect")]
  public static extern void Producer_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, Producer.SwigDelegateProducer_0 delegate0, Producer.SwigDelegateProducer_1 delegate1, Producer.SwigDelegateProducer_2 delegate2, Producer.SwigDelegateProducer_3 delegate3, Producer.SwigDelegateProducer_4 delegate4);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_OrderConsumer")]
  public static extern global::System.IntPtr new_OrderConsumer();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_OrderConsumer")]
  public static extern void delete_OrderConsumer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderConsumer_start")]
  public static extern void OrderConsumer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderConsumer_shutdown")]
  public static extern void OrderConsumer_shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderConsumer_subscribe")]
  public static extern void OrderConsumer_subscribe(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderConsumer_director_connect")]
  public static extern void OrderConsumer_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, OrderConsumer.SwigDelegateOrderConsumer_0 delegate0, OrderConsumer.SwigDelegateOrderConsumer_1 delegate1, OrderConsumer.SwigDelegateOrderConsumer_2 delegate2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_OrderProducer")]
  public static extern global::System.IntPtr new_OrderProducer();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_OrderProducer")]
  public static extern void delete_OrderProducer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderProducer_start")]
  public static extern void OrderProducer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderProducer_shutdown")]
  public static extern void OrderProducer_shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderProducer_send")]
  public static extern global::System.IntPtr OrderProducer_send(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_OrderProducer_director_connect")]
  public static extern void OrderProducer_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, OrderProducer.SwigDelegateOrderProducer_0 delegate0, OrderProducer.SwigDelegateOrderProducer_1 delegate1, OrderProducer.SwigDelegateOrderProducer_2 delegate2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_PushConsumer")]
  public static extern global::System.IntPtr new_PushConsumer();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_PushConsumer")]
  public static extern void delete_PushConsumer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PushConsumer_start")]
  public static extern void PushConsumer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PushConsumer_shutdown")]
  public static extern void PushConsumer_shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PushConsumer_subscribe")]
  public static extern void PushConsumer_subscribe(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PushConsumer_director_connect")]
  public static extern void PushConsumer_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, PushConsumer.SwigDelegatePushConsumer_0 delegate0, PushConsumer.SwigDelegatePushConsumer_1 delegate1, PushConsumer.SwigDelegatePushConsumer_2 delegate2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_PullConsumer")]
  public static extern global::System.IntPtr new_PullConsumer();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_PullConsumer")]
  public static extern void delete_PullConsumer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_start")]
  public static extern void PullConsumer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_shutdown")]
  public static extern void PullConsumer_shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_fetchSubscribeMessageQueues")]
  public static extern void PullConsumer_fetchSubscribeMessageQueues(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_pull")]
  public static extern global::System.IntPtr PullConsumer_pull(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, long jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_searchOffset")]
  public static extern long PullConsumer_searchOffset(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_maxOffset")]
  public static extern long PullConsumer_maxOffset(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_minOffset")]
  public static extern long PullConsumer_minOffset(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_updateConsumeOffset")]
  public static extern void PullConsumer_updateConsumeOffset(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, long jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_removeConsumeOffset")]
  public static extern void PullConsumer_removeConsumeOffset(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_fetchConsumeOffset")]
  public static extern long PullConsumer_fetchConsumeOffset(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_persistConsumerOffset4PullConsumer")]
  public static extern void PullConsumer_persistConsumerOffset4PullConsumer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_PullConsumer_director_connect")]
  public static extern void PullConsumer_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, PullConsumer.SwigDelegatePullConsumer_0 delegate0, PullConsumer.SwigDelegatePullConsumer_1 delegate1, PullConsumer.SwigDelegatePullConsumer_2 delegate2, PullConsumer.SwigDelegatePullConsumer_3 delegate3, PullConsumer.SwigDelegatePullConsumer_4 delegate4, PullConsumer.SwigDelegatePullConsumer_5 delegate5, PullConsumer.SwigDelegatePullConsumer_6 delegate6, PullConsumer.SwigDelegatePullConsumer_7 delegate7, PullConsumer.SwigDelegatePullConsumer_8 delegate8, PullConsumer.SwigDelegatePullConsumer_9 delegate9, PullConsumer.SwigDelegatePullConsumer_10 delegate10);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_TransactionProducer")]
  public static extern void delete_TransactionProducer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_TransactionProducer_start")]
  public static extern void TransactionProducer_start(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_TransactionProducer_shutdown")]
  public static extern void TransactionProducer_shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_TransactionProducer_send")]
  public static extern global::System.IntPtr TransactionProducer_send(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_ONSFactoryProperty")]
  public static extern global::System.IntPtr new_ONSFactoryProperty();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_ONSFactoryProperty")]
  public static extern void delete_ONSFactoryProperty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_checkValidityOfFactoryProperties")]
  public static extern bool ONSFactoryProperty_checkValidityOfFactoryProperties(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getLogPath")]
  public static extern string ONSFactoryProperty_getLogPath(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setSendMsgTimeout")]
  public static extern void ONSFactoryProperty_setSendMsgTimeout(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setSendMsgRetryTimes")]
  public static extern void ONSFactoryProperty_setSendMsgRetryTimes(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setMaxMsgCacheSize")]
  public static extern void ONSFactoryProperty_setMaxMsgCacheSize(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setOnsTraceSwitch")]
  public static extern void ONSFactoryProperty_setOnsTraceSwitch(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setOnsChannel")]
  public static extern void ONSFactoryProperty_setOnsChannel(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setFactoryProperty")]
  public static extern void ONSFactoryProperty_setFactoryProperty(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_setFactoryProperties")]
  public static extern void ONSFactoryProperty_setFactoryProperties(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getFactoryProperties")]
  public static extern global::System.IntPtr ONSFactoryProperty_getFactoryProperties(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getProducerId")]
  public static extern string ONSFactoryProperty_getProducerId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getConsumerId")]
  public static extern string ONSFactoryProperty_getConsumerId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getPublishTopics")]
  public static extern string ONSFactoryProperty_getPublishTopics(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getMessageModel")]
  public static extern string ONSFactoryProperty_getMessageModel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getSendMsgTimeout")]
  public static extern int ONSFactoryProperty_getSendMsgTimeout(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getSendMsgRetryTimes")]
  public static extern int ONSFactoryProperty_getSendMsgRetryTimes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getConsumeThreadNums")]
  public static extern int ONSFactoryProperty_getConsumeThreadNums(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getMaxMsgCacheSize")]
  public static extern int ONSFactoryProperty_getMaxMsgCacheSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getOnsChannel")]
  public static extern int ONSFactoryProperty_getOnsChannel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getChannel")]
  public static extern string ONSFactoryProperty_getChannel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getMessageContent")]
  public static extern string ONSFactoryProperty_getMessageContent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getNameSrvAddr")]
  public static extern string ONSFactoryProperty_getNameSrvAddr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getNameSrvDomain")]
  public static extern string ONSFactoryProperty_getNameSrvDomain(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getAccessKey")]
  public static extern string ONSFactoryProperty_getAccessKey(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getSecretKey")]
  public static extern string ONSFactoryProperty_getSecretKey(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_getOnsTraceSwitch")]
  public static extern bool ONSFactoryProperty_getOnsTraceSwitch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_LogPath_set")]
  public static extern void ONSFactoryProperty_LogPath_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_LogPath_get")]
  public static extern string ONSFactoryProperty_LogPath_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ProducerId_set")]
  public static extern void ONSFactoryProperty_ProducerId_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ProducerId_get")]
  public static extern string ONSFactoryProperty_ProducerId_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ConsumerId_set")]
  public static extern void ONSFactoryProperty_ConsumerId_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ConsumerId_get")]
  public static extern string ONSFactoryProperty_ConsumerId_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_PublishTopics_set")]
  public static extern void ONSFactoryProperty_PublishTopics_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_PublishTopics_get")]
  public static extern string ONSFactoryProperty_PublishTopics_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_MsgContent_set")]
  public static extern void ONSFactoryProperty_MsgContent_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_MsgContent_get")]
  public static extern string ONSFactoryProperty_MsgContent_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ONSAddr_set")]
  public static extern void ONSFactoryProperty_ONSAddr_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ONSAddr_get")]
  public static extern string ONSFactoryProperty_ONSAddr_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_AccessKey_set")]
  public static extern void ONSFactoryProperty_AccessKey_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_AccessKey_get")]
  public static extern string ONSFactoryProperty_AccessKey_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_SecretKey_set")]
  public static extern void ONSFactoryProperty_SecretKey_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_SecretKey_get")]
  public static extern string ONSFactoryProperty_SecretKey_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_MessageModel_set")]
  public static extern void ONSFactoryProperty_MessageModel_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_MessageModel_get")]
  public static extern string ONSFactoryProperty_MessageModel_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_BROADCASTING_set")]
  public static extern void ONSFactoryProperty_BROADCASTING_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_BROADCASTING_get")]
  public static extern string ONSFactoryProperty_BROADCASTING_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_CLUSTERING_set")]
  public static extern void ONSFactoryProperty_CLUSTERING_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_CLUSTERING_get")]
  public static extern string ONSFactoryProperty_CLUSTERING_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_SendMsgTimeoutMillis_set")]
  public static extern void ONSFactoryProperty_SendMsgTimeoutMillis_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_SendMsgTimeoutMillis_get")]
  public static extern string ONSFactoryProperty_SendMsgTimeoutMillis_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_NAMESRV_ADDR_set")]
  public static extern void ONSFactoryProperty_NAMESRV_ADDR_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_NAMESRV_ADDR_get")]
  public static extern string ONSFactoryProperty_NAMESRV_ADDR_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ConsumeThreadNums_set")]
  public static extern void ONSFactoryProperty_ConsumeThreadNums_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_ConsumeThreadNums_get")]
  public static extern string ONSFactoryProperty_ConsumeThreadNums_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_OnsChannel_set")]
  public static extern void ONSFactoryProperty_OnsChannel_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_OnsChannel_get")]
  public static extern string ONSFactoryProperty_OnsChannel_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_MaxMsgCacheSize_set")]
  public static extern void ONSFactoryProperty_MaxMsgCacheSize_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_MaxMsgCacheSize_get")]
  public static extern string ONSFactoryProperty_MaxMsgCacheSize_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_OnsTraceSwitch_set")]
  public static extern void ONSFactoryProperty_OnsTraceSwitch_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_OnsTraceSwitch_get")]
  public static extern string ONSFactoryProperty_OnsTraceSwitch_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_SendMsgRetryTimes_set")]
  public static extern void ONSFactoryProperty_SendMsgRetryTimes_set(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryProperty_SendMsgRetryTimes_get")]
  public static extern string ONSFactoryProperty_SendMsgRetryTimes_get();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_new_ONSFactoryAPI")]
  public static extern global::System.IntPtr new_ONSFactoryAPI();

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_ONSFactoryAPI")]
  public static extern void delete_ONSFactoryAPI(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryAPI_createProducer")]
  public static extern global::System.IntPtr ONSFactoryAPI_createProducer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryAPI_createOrderProducer")]
  public static extern global::System.IntPtr ONSFactoryAPI_createOrderProducer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryAPI_createOrderConsumer")]
  public static extern global::System.IntPtr ONSFactoryAPI_createOrderConsumer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryAPI_createTransactionProducer")]
  public static extern global::System.IntPtr ONSFactoryAPI_createTransactionProducer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryAPI_createPullConsumer")]
  public static extern global::System.IntPtr ONSFactoryAPI_createPullConsumer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactoryAPI_createPushConsumer")]
  public static extern global::System.IntPtr ONSFactoryAPI_createPushConsumer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_delete_ONSFactory")]
  public static extern void delete_ONSFactory(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("ONSClient4CPP", EntryPoint="CSharp_ons_ONSFactory_getInstance")]
  public static extern global::System.IntPtr ONSFactory_getInstance();
}

}
