//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ons {

public class SystemPropKey : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SystemPropKey(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SystemPropKey obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SystemPropKey() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ONSClient4CPPPINVOKE.delete_SystemPropKey(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SystemPropKey() : this(ONSClient4CPPPINVOKE.new_SystemPropKey(), true) {
  }

  public static string TAG {
    set {
      ONSClient4CPPPINVOKE.SystemPropKey_TAG_set(value);
    } 
    get {
      string ret = ONSClient4CPPPINVOKE.SystemPropKey_TAG_get();
      return ret;
    } 
  }

  public static string KEY {
    set {
      ONSClient4CPPPINVOKE.SystemPropKey_KEY_set(value);
    } 
    get {
      string ret = ONSClient4CPPPINVOKE.SystemPropKey_KEY_get();
      return ret;
    } 
  }

  public static string MSGID {
    set {
      ONSClient4CPPPINVOKE.SystemPropKey_MSGID_set(value);
    } 
    get {
      string ret = ONSClient4CPPPINVOKE.SystemPropKey_MSGID_get();
      return ret;
    } 
  }

  public static string RECONSUMETIMES {
    set {
      ONSClient4CPPPINVOKE.SystemPropKey_RECONSUMETIMES_set(value);
    } 
    get {
      string ret = ONSClient4CPPPINVOKE.SystemPropKey_RECONSUMETIMES_get();
      return ret;
    } 
  }

  public static string STARTDELIVERTIME {
    set {
      ONSClient4CPPPINVOKE.SystemPropKey_STARTDELIVERTIME_set(value);
    } 
    get {
      string ret = ONSClient4CPPPINVOKE.SystemPropKey_STARTDELIVERTIME_get();
      return ret;
    } 
  }

}

}
